global.logger = require('./src/miscellaneous/logger')
global.webhook = require('./src/miscellaneous/webhooklogger')
require('./src/miscellaneous/logger')
require('dotenv').config()
require('./src/bot/')
